### ISSUE TITLE
Generate perturbation for arbitrarily sized images

### ISSUE THREAD

**Issue by alexmstaff** [git-disl/TOG#6]
I'm exploring a black-box attack, but the model under attack has very poor performance on the images after being rescaled and padded.

I would like to generate an adversarial perturbation without rescaling the image.

**Comment by khchow-gt** [comment]
Which model are you using? If it is YOLOv3 or SSD, resizing inputs is necessary because these techniques require a specific resolution of the input image (e.g., for SSD300, it must be 300x300). If you are using Faster R-CNN instead, you can modify the image preprocessing component and send the image with the original resolution to the model.

**Comment by alexmstaff** [comment]
I'm using the YOLOv3 model and attacking a YOLOv3 model trained using [darknet](https://github.com/AlexeyAB/darknet). The problem I'm facing is that even though the darknet model downsamples images to 416 x 416, it loses most of its performance on the images that have been processed by the letterbox_image function https://github.com/git-disl/TOG/blob/3b273c272ee9a4ebac5911aac114e97640b2910c/yolov3_utils/utils.py#L18

**Comment by khchow-gt** [comment]
Unfortunately, this downsampling is requested by YOLOv3. There are two solutions you may explore:

1. Use YOLOv3 with a higher resolution (but it should be a multiple of 32)
2. Use Faster R-CNN as it doesn't require downsampling

**Comment by alexmstaff** [comment]
Right! I'll try these options.
